name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: genetic_schedule_solver
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/genetic_schedule_solver
        if-no-files-found: warn
        overwrite: true
          
